### ISSUE TITLE
Crash attaching horse to grindstone

### ISSUE THREAD

**Issue by rckymtnrfc** [GoryMoon/HorsePower#10]
I noticed JEI was showing a recipe for planks from logs using the grindstone (it also showed the chopper recipe).

I was going to test to see if this actually worked (it's not a recipe in my configs for the grindstone) but I received the following crash when attached the horse to the grindstone.

https://pastebin.com/w6xDQUzj

Forge 2413
Horse Power 1.12-2.3.0.35

Thank you,

**Comment by GoryMoon** [comment]
The crash should be fixed in 2.3.1.36 that is available on curse.
I can't reproduce the issue with logs to planks recipe is showing in the grindstone recipe category.

**Comment by rckymtnrfc** [comment]
I'll double check my config and make sure I didn't goof something with the logs showing in JEI.  If needed, I'll open aanother issue for that.   Thanks for fix on the crash.

**Comment by GoryMoon** [comment]
Oh, did you run on it on a server? If so I might found the issue...

**Comment by rckymtnrfc** [comment]
Yes, this is on a server.

**Comment by GoryMoon** [comment]
Ok, so that must have been the issue in that case. Will have an update for that with the next version, currently working on your request of a manual chopping block so it will take a little bit.

**Comment by rckymtnrfc** [comment]
That's awesome!  Thanks for using my suggestion!
