### ISSUE TITLE
[1.12] Ore Dictionary recipes do not add all matching items

### ISSUE THREAD

**Issue by angelnc1989** [GoryMoon/HorsePower#13]
I set up some ore dictionary recipes for the Grindstone with CraftTweaker scripts and they don't work as intended.
`Grindstone.add(<ore:ingotIron>, <immersiveengineering:metal:18>, 8, true);
Grindstone.add(<ore:oreIron>, <immersiveengineering:metal:18> * 2, 16, true, <immersiveengineering:metal:13>, 10);`
This adds `Iron Ingot -> Iron Grit,
Iron Ore -> Iron Grit * 2,
LevelUp2 Iron Chunk -> Iron Grit * 2`
But it doesn't add `Gravel Ores Iron Gravel Ore -> Iron Grit * 2`
Iron Ore, Iron Chunk and Iron Gravel Ore are all member of oreIron.

Another example is `Grindstone.add(<ore:listAllgrain>, <harvestcraft:flouritem> * 2, 8, true);
` doesn't add anything. Adding them all one by one works fine. 
`Grindstone.add(<minecraft:wheat>, <harvestcraft:flouritem> * 2, 8, true);
Grindstone.add(<harvestcraft:barleyitem>, <harvestcraft:flouritem> * 2, 8, true);
Grindstone.add(<harvestcraft:oatsitem>, <harvestcraft:flouritem> * 2, 8, true);
Grindstone.add(<harvestcraft:ryeitem>, <harvestcraft:flouritem> * 2, 8, true);`

This `Grindstone.add(<ore:blockGlass>, <minecraft:sand>, 12, true);
` on the other hand works perfectly fine and adds every variation of glass. (All seperate though and not as one entry with changing items in JEI)

**Comment by GoryMoon** [comment]
Should be fixed in the latest version

**Comment by angelnc1989** [comment]
Doesn't seem to be fixed for me.

**Comment by GoryMoon** [comment]
Definitely fixed in the latest now, made sure the recipes are loaded really late, at the point where you should do mod interactions and all registrations of items, blocks and ore dicts, Gravel Ores don't do that before that point and my mod was loaded before because gravel ores forces it to load last.

**Comment by GoryMoon** [comment]
Btw, Harvestcraft was working in that last version but not Gravel Ores.

**Comment by angelnc1989** [comment]
Now it is working. I actually only checked Gravel Ores last time. Thanks! Keep up the good work!
