### ISSUE TITLE
Default configuration adds unusable recipes for chopping blocks

### ISSUE THREAD

**Issue by josephcsible** [GoryMoon/HorsePower#14]
The default configuration of Horse Power adds a crafting recipe that lets individual logs be turned into chopping blocks. However, this is the same as the vanilla recipe for planks, which isn't removed. As a result, the recipes conflict, and only the planks recipe is usable.

Versions:
Minecraft 1.12
Minecraft Forge 14.21.1.2443
Horse Power 2.5.2.44
JEI 4.7.4.81

![2017-08-05_19 08 15](https://user-images.githubusercontent.com/16061266/28999363-f05720dc-7a11-11e7-9421-ed137bfd8840.png)

**Comment by GoryMoon** [comment]
Fixed in the latest version
