### ISSUE TITLE
horse power 1.12

### ISSUE THREAD

**Issue by CharCharthemonkey** [GoryMoon/HorsePower#15]
i tried to set the configs to use the horsepower items for getting stuff i even coppied the 1.11.2 configs (mostly) to 1.12 (basically just changed the ones in 1.12 to match 1.11.2 version but it wouldnt work even with a MC restart so pretty plz help?

**Comment by GoryMoon** [comment]
What was it that didn't work?

If it was that you used separated grindstone recipes and not separated chopping block recipes and the hand grindstone didn't work, that is fixed in a version going up in a few minutes.

**Comment by CharCharthemonkey** [comment]
i used both seperate grindstone and chopping block recipes and neither worked also when i turned on ore dict for the mod it would crash out my game

**Comment by CharCharthemonkey** [comment]
if i knew how i could send u the config with the changes i did to enable the features in question and the crash reports for the pack

**Comment by GoryMoon** [comment]
You can upload it to [pastebin.com](http://pastebin.com) and then paste the links here. 

Also what version of the mod are you using?

**Comment by CharCharthemonkey** [comment]
its the latest version for 1.12 on the twitch app  https://pastebin.com/ruwuumpv  for the config and https://pastebin.com/vQZKrsBv  for the crash log

**Comment by CharCharthemonkey** [comment]
the version of horsepower is 1.12.2.5.5.48 but its been doing that since 2-3 versions back

**Comment by GoryMoon** [comment]
That config isn't causing that crash, anyway got a fix for that crash going up in a little while. For that crash "Show Ore Dictionaries" needs to be true.

**Comment by CharCharthemonkey** [comment]
but weirdly i set it to true and thats wat causes the crash

**Comment by CharCharthemonkey** [comment]
also removing vanilla recipes (basically making it so u had to use the choppingblocks/grindstone/presser) doesnt work either if that helps

**Comment by CharCharthemonkey** [comment]
heres wat it shows for making the manual chopper block even know the config is turned on to allow it and turned off to allow vanilla recipes
![2017-08-09_16 02 27](https://user-images.githubusercontent.com/30783285/29144592-1dc77f8e-7d1f-11e7-9ddd-28574e0abae7.png)

**Comment by GoryMoon** [comment]
I don't remove the log to planks recipe and the recipe for the chopping block isn't the one that you used there, you need a log and a flint to make it

**Comment by CharCharthemonkey** [comment]
but i was trying to make the manual one that is shown in 1.11.2 so ud have to use that to get the 1st planks to make the upgraded ones for horses and thats the one thats not showing for me

**Comment by GoryMoon** [comment]
To combat the recipe of log to planks, the recipe for the manual chopping block is a log and a flint in a crafting grind, shapless

**Comment by CharCharthemonkey** [comment]
ohhhh that makes more sense thank you but y does it still show the recipe for log to planks with the config turned off?
