### ISSUE TITLE
Compat w/ Binnie's Trees

### ISSUE THREAD

**Issue by zjgruber** [GoryMoon/HorsePower#17]
They definitely don't work out of the box. The planks are "extratrees:logs.0" with the number being 0-9, with metadata of 0-3 (so a total of 40 logs). I tried putting them into the config, but I think maybe the "." in the name breaks them, or I have the syntax mixed up, because I can't seem to get them to work despite checking and double checking them.

Example:
`extratrees:logs.0:0-extratrees:planks.0:0@4-1`
through:
`extratrees:logs.9:3-extratrees:planks.9:3@4-1`

**Comment by GoryMoon** [comment]
It does work with Binnie's Trees, you just missed how the name and meta of the planks works, here is all the recipes for their logs to planks as the crafting recipe is

> extratrees:logs.0:0-extratrees:planks.0:0@4-1
extratrees:logs.0:1-extratrees:planks.0:1@4-1
extratrees:logs.0:2-extratrees:planks.0:2@4-1
extratrees:logs.0:3-extratrees:planks.0:3@4-1
extratrees:logs.1:0-extratrees:planks.0:4@4-1
extratrees:logs.1:1-extratrees:planks.0:5@4-1
extratrees:logs.1:2-extratrees:planks.0:6@4-1
extratrees:logs.1:3-extratrees:planks.0:7@4-1
extratrees:logs.2:0-extratrees:planks.0:8@4-1
extratrees:logs.2:1-extratrees:planks.0:9@4-1
extratrees:logs.2:2-extratrees:planks.0:10@4-1
extratrees:logs.2:3-extratrees:planks.0:11@4-1
extratrees:logs.3:0-extratrees:planks.0:12@4-1
extratrees:logs.3:1-extratrees:planks.0:13@4-1
extratrees:logs.3:2-extratrees:planks.0:14@4-1
extratrees:logs.3:3-extratrees:planks.0:15@4-1
extratrees:logs.4:0-extratrees:planks.1:0@4-1
extratrees:logs.4:1-extratrees:planks.1:1@4-1
extratrees:logs.4:2-extratrees:planks.1:2@4-1
extratrees:logs.4:3-extratrees:planks.1:3@4-1
extratrees:logs.5:0-extratrees:planks.1:4@4-1
extratrees:logs.5:1-extratrees:planks.1:5@4-1
extratrees:logs.5:2-extratrees:planks.1:6@4-1
extratrees:logs.5:3-extratrees:planks.1:7@4-1
extratrees:logs.6:0-extratrees:planks.1:8@4-1
extratrees:logs.6:1-extratrees:planks.1:9@4-1
extratrees:logs.6:2-extratrees:planks.1:10@4-1
extratrees:logs.6:3-extratrees:planks.1:11@4-1
extratrees:logs.7:0-extratrees:planks.1:12@4-1
extratrees:logs.7:1-extratrees:planks.1:13@4-1
extratrees:logs.7:2-extratrees:planks.1:14@4-1
extratrees:logs.7:3-extratrees:planks.1:15@4-1
extratrees:logs.8:1-extratrees:planks.2:1@4-1
extratrees:logs.8:2-extratrees:planks.2:2@4-1
extratrees:logs.8:3-extratrees:planks.2:3@4-1
extratrees:logs.9:1-extratrees:planks.1:0@4-1
extratrees:logs.9:2-extratrees:planks.0:15@4-1
extratrees:logs.9:3-minecraft:planks:3@4-1
