### ISSUE TITLE
Adding mobs to grindstone

### ISSUE THREAD

**Issue by Y0ungSandwich** [GoryMoon/HorsePower#18]
I added 

     S:"Mob List" <
			net.xalcon.chococraft.common.entities.EntityChocobo
			
         >

But no luck. Is this mob not supported or am I doing something else wrong?

**Comment by GoryMoon** [comment]
What version of Minecraft, Forge, Horsepower and Chococraft are you using, it works for me in 1.12

**Comment by Y0ungSandwich** [comment]
Yeah sorry nothing changed but I just re did the config while adding ores and it worked. Must of been a typo or something o.O
