### ISSUE TITLE
[1.12.1] All recipes added twice in JEI

### ISSUE THREAD

**Issue by angelnc1989** [GoryMoon/HorsePower#19]
Minecraft 1.12.1
Forge 14.22.0.2474
HorsePower 2.5.6.49

![image](https://user-images.githubusercontent.com/5382585/30327287-c88ab596-97cb-11e7-99e5-a6a5a24ab925.png)
![image](https://user-images.githubusercontent.com/5382585/30327340-fc81a670-97cb-11e7-8629-33b4adefab70.png)

**Comment by angelnc1989** [comment]
The issue persists in newer versions. I am currently on 2.5.7.51.

**Comment by GoryMoon** [comment]
Fixed in the latest release 2.5.8.52
