### ISSUE TITLE
Odd difficulty adding Roost chicken items to grinding recipes

### ISSUE THREAD

**Issue by esotericist** [GoryMoon/HorsePower#21]
Long story short I decided to make the inventory-item version of the chickens from Roost directly grindable to chicken nuggets using Horse Power.

I set them up in the config as so:
```
            roost:chicken:*${Chicken:"minecraft:chicken"}-vanillafoodpantry:meat_portion:0@9-12-vanillafoodpantry:meat_portion:0@4-50
```

but even though they show up in JEI as usable in the grinder when I check the uses of the items I have...
![JEI screenshot](https://media.discordapp.net/attachments/360995219321126935/380783695365144576/2017-11-16_10.14.30.png?width=1083&height=562)

... they don't seem to actually want to go into the grindstone.
![Hopper screenshot](https://media.discordapp.net/attachments/360995219321126935/380783699131760651/2017-11-16_10.14.32.png?width=1083&height=562)

Other items successfully get pushed through, and other recipes I've added work. I had originally tried it without specifying the NBT, but while that would show up in the horsepower recipes, it wouldn't show up for the 'uses' of the chickens in inventory. They do show up that way with the NBT specified. 

Is there something I'm doing wrong?

**Comment by GoryMoon** [comment]
If you removed the * for meta it will work or set it to 0, this should work anyway and I have fixed it in a new version going up on curse atm.

**Comment by esotericist** [comment]
Thank you for the prompt response!
