### ISSUE TITLE
[CraftTweaker] Add information about configs that still effect CraftTweaker recipes to wiki

### ISSUE THREAD

**Issue by justinrusso** [GoryMoon/HorsePower#23]
I am trying to use CraftTweaker to make a recipe for an item. I want it so manual is 4x, and auto is 2x, but I seem to be unable to get it working. I'm not sure if I'm just doing something wrong, but at this point I'm not sure what I've done wrong.

Script: https://gist.github.com/justinrusso/c4b2b69a123965ee10fe5fcabd2ea7c2

I end up with this as the result:
![image](https://user-images.githubusercontent.com/25138621/34541218-62e8fd50-f0a5-11e7-9327-66e8175ad10b.png)

Using an iron axe it takes 16 hits, and the automatic displays as 4x in JEI which is already incorrect.

**Comment by GoryMoon** [comment]
Have  a look at the config.
For the manual chopping block this applies to the crafttweaker recipes as well:
```
# Uses the same syntax as the regular chopping recipes, the only difference is that the time is the amount of chopps
# These recipes are only used when the config to separate them is enabled
```

```
# If the separate list of recipes should be used for the chopping block
B:"Separate Chopping Recipes"=false
```

This config entry is relevant to the amount of chops it took with the manual one
```
# The amount of chopps the time value in the horse chopping recipes should be multiplied with if recipes isn't separated
# If the recipes are separate this isn't used, instead the recipe value is used
I:"Chopping Multiplier"=4
```
If there is something else just say.

**Comment by GoryMoon** [comment]
Updated the wiki page
