### ISSUE TITLE
Suggestion: Allow presser to output fluids

### ISSUE THREAD

**Issue by WrongWeekend** [GoryMoon/HorsePower#25]
I'd really like the animal driven presser in your mod to support liquid outputs, so players can add recipes for pressing cactus into water, seeds into various mods' oil, apples and grapes into Rustic's juices, and so on. Players should be able to use a bucket or bottle (if supported) to remove the fluid, or possibly output it with a pipe from the bottom.

**Comment by GoryMoon** [comment]
A version going up on curse atm contains this
