### ISSUE TITLE
[Bug] Grindstone

### ISSUE THREAD

**Issue by jursamaj** [GoryMoon/HorsePower#26]
I've noticed that with the grindstone, using shift right-click to remove things from the input side doesn't work if I have anything in the off hand.  Likewise, with anything in the off hand, I can't pick up stuff from the output side if there is anything still in the input side.  In both cases, it just spins the stone.  I don't know if there's anything you can do about that, or if it's a limitation of how MC handles clicking while holding anything in the off hand.

**Comment by GoryMoon** [comment]
This is an issue with how vanilla handles right clicking on blocks.
Could bypass it in one way but don't know what that would do to some other mod or future mod that you need to shift right click a block with.
