### ISSUE TITLE
Crash when breaking blocks in creative mode

### ISSUE THREAD

**Issue by T4ge** [GoryMoon/HorsePower#3]
Crashed when breaking blocks in Creative mode
Honestly they all seem to be the same by just quickly glancing over them.
I still added them all just in case.

Minecraft 1.11.2
Forge 13.20.1.2393
HorsePower 1.3.0.16

Horse Grindstone
https://pastebin.com/raw/Nb595UnN

Horse Chopping Block
https://pastebin.com/raw/RBNBrtz4

Hand Grindstone
https://pastebin.com/raw/MQ98PabZ

**Comment by Omnimetatron** [comment]
Snap!
https://pastebin.com/raw/ThY8K8nK

**Comment by GoryMoon** [comment]
Sorry for not responding to this earlier, didn't get any notification about this.
This is fixed in HorsePower 1.4.1.21
