### ISSUE TITLE
Broken Chopping Block Rendering

### ISSUE THREAD

**Issue by UnlimatedStone9** [GoryMoon/HorsePower#31]
I honestly have no clue what causes this but quite often while building custom Modpacks I have noticed that both chopping blocks and horse chopping blocks will be invisible when placed down and in the inventory will all render as oak chopping blocks

![2018-07-28_01 05 27](https://user-images.githubusercontent.com/40124890/43350804-7b9a0534-9202-11e8-8d5c-49e0e6e3c870.png)

![2018-07-28_01 04 04](https://user-images.githubusercontent.com/40124890/43350807-8462d204-9202-11e8-8802-1922e905dbc6.png)

**Comment by artdude543** [comment]
This is the same issue we're having with SevTech: Ages when working on the next major update. We thought it's something we are doing wrong or a mod update is causing a conflict somewhere. But we've so far not been able to track down who/what's causing this issue.

**Comment by UnlimatedStone9** [comment]
I've been questioning a few mods and I'm currently going over what is installed but its going to take a while as its quite a large pack I'm making, I intend to report which mod breaks it here as soon as I figure it out

**Comment by UnlimatedStone9** [comment]
It's quite an old problem I've had

**Comment by UnlimatedStone9** [comment]
I see no reason why chopping blocks render incorrectly I've tried removing mods, having the mod load last and even changing its update version but nothing appears to break it, I'm lost for words here

**Comment by UnlimatedStone9** [comment]
@artdude543 I believe I have traced the problem down to being an incompatibility with newer versions of Better With Mods, I installed BWM into a new pack earlier and only then were the chopping blocks broken

**Comment by UnlimatedStone9** [comment]
This is currently going to be resolved, I have discussed the issues with primetoxinz and it was discovered that the ConnectedTexturesMod causes the error rendering chisel and other mods unusable when uninstalled to fix the issue
