### ISSUE TITLE
Using off-hand to place blocks onto chopping block

### ISSUE THREAD

**Issue by SeriousCreeper** [GoryMoon/HorsePower#37]
Heya,

prior to using Horsepower, i was using Survivalist, which also adds a chopping block. One nice feature of that mod is that you can have logs in your off-hand and right click the chopping block to place the logs, while holding your axe in the main hand to chop. It made the process of chopping blocks a bit nicer, since you didnt have to select a different item in your hot bar in between crafts. 

Would it be possible to get the off-hand feature added to horsepower as well? 

Cheers,
SC

**Comment by GoryMoon** [comment]
This was a feature I don't remember why it was removed but it's back in the latest version available on curse.
