### ISSUE TITLE
Could not find (***) mob class.

### ISSUE THREAD

**Issue by Gunner76th** [GoryMoon/HorsePower#39]
Modpack: Sky Factory 4
MC Version: 1.12.2
Forge Version: 2831
Horepower version: HorsePower-1.12.2-2.6.3.72.jar
[horsepower.cfg.txt](https://github.com/GoryMoon/HorsePower/files/3244405/horsepower.cfg.txt)

I have noticed on our server that the below listed error is appearing on the console. 
I have attached the config in use for the server in case it is needed to help trouble shoot the issue. Extension changed to .txt due to github file extension restrictions. 

`[22:28:08] [Server thread/ERROR] [HorsePower]: Error in config, could not find (pokefenn.totemic.entity.animal.EntityBaldEagle) mob class, mod for entity might not be installed
[22:28:08] [Server thread/ERROR] [HorsePower]: Error in config, could not find (pokefenn.totemic.entity.animal.EntityBuffalo) mob class, mod for entity might not be installed
`

![image](https://user-images.githubusercontent.com/5566872/58755965-be200b80-84bc-11e9-8e77-a95e2d5a9f32.png)

**Comment by GoryMoon** [comment]
If you don't want the console logging remove the mobs from the config/make an issue on the SF4 repo.
They are not shipped by default, they are added by the modpack.
The logging is intended to show that you either typed wrong or it's missing so you can remove it.
