### ISSUE TITLE
Crash when attaching horse to grindstone

### ISSUE THREAD

**Issue by T4ge** [GoryMoon/HorsePower#4]
Done in creative mode if that changes anything. 

Minecraft 1.11.2
Forge 13.20.1.2393
HorsePower 1.3.0.16
https://pastebin.com/raw/AW8HyGxQ

**Comment by GoryMoon** [comment]
Sorry for not responding to this earlier, didn't get any notification about this.
This is fixed in HorsePower 1.4.1.21
