### ISSUE TITLE
[Bug] Press CraftTweaker and Ore Dictionary

### ISSUE THREAD

**Issue by faeldray** [GoryMoon/HorsePower#46]
In a CraftTweaker script, if an ore dictionary item is used as an input for the press, it ignores the amount. Example:
`mods.horsepower.Press.add(<ore:ingotAluminum> * 3, <embers:plate_aluminum> * 2);`
(note the amount of ingots)
![image](https://user-images.githubusercontent.com/967709/66593026-d505f700-eb5b-11e9-8d62-78508bfd56d8.png)

If an non-ore-dictionary item is used, the amount works just fine:
`mods.horsepower.Press.add(<evilcraft:werewolf_flesh> * 2, <minecraft:leather>);`
![image](https://user-images.githubusercontent.com/967709/66593303-5b223d80-eb5c-11e9-945b-46e0359aa4b5.png)

**Comment by GoryMoon** [comment]
Looks like this is a limitation on crafttweakers side, even if I support it the underlaying system for ore dicts in crafttweaker only has the size of 1 no matter what you input.

**Comment by faeldray** [comment]
Ah, well that sucks. It's not a big deal though, I only have a few recipes with that issue so I can just use non-ore-dictionary items.
