### ISSUE TITLE
Secondary drops removed  in 1.12

### ISSUE THREAD

**Issue by belug23** [GoryMoon/HorsePower#5]
Hi, I want to add a recipe that add a secondary, but while looking at the documentation, it seems that in 1.12 you removed that option. Is it a 1.12 limitation?

**Comment by GoryMoon** [comment]
The reason is that I made it in 1.11.2 and haven't ported it to 1.12 yet, it's in the works, will be done soon.

**Comment by GoryMoon** [comment]
Updated the latest version on Curse with the secondary outputs.

**Comment by belug23** [comment]
Thank you really much!
