### ISSUE TITLE
Use CapabilityItemHandler not IInventory!

### ISSUE THREAD

**Issue by primetoxinz** [GoryMoon/HorsePower#8]
IInventory is 99% no longer support for inventories, you should use Capabilities.
Nothing can pull from your inventories as Darkosto just found on stream.
If you need help with how they work let me know.

**Comment by GoryMoon** [comment]
Thought I had support for Capabilities, saw that I had missed a part to make it work.
Just came into the stream when he was testing that and I started working on it, have been lurking since then, have moved to only use Capabilities now.
