### ISSUE TITLE
Crash with CraftTweaker2

### ISSUE THREAD

**Issue by rckymtnrfc** [GoryMoon/HorsePower#9]
I'm seeing a crash when I have CraftTweaker2 and Horse Power installed.

https://pastebin.com/Gxr9ZLQZ

I'm using Forge 2413

Thanks!

**Comment by GoryMoon** [comment]
This is fixed in the latest version and the support for crafttweaker is now added to the 1.12 version

**Comment by rckymtnrfc** [comment]
Wow, thanks for the quick fix.  Really enjoying your mod.
